### PR TITLE
Updated documentation formatting, fixed spelling errors etc.

### PR DESCRIPTION
**Pull request by sveinbjornt**
Not much in the way of a contribution, but I improved documentation formatting, fixed some spelling mistakes/typos and added a license file. Thank you for your great work on this!

### CODE REVIEW

**Comment by Thalhammer** [comment]
I am not a native speaker, so even such simple things are highly appreciated :)

**Comment by sveinbjornt** [comment]
@Thalhammer I'm interested in helping any way I can. I'm using Snowboy for hotword detection in a cross-platform digital assistant currently under development. This technology is very important to us since it is significantly improves on Pocketsphinx, which we used previously. I'm afraid I don't know much about machine learning or reverse engineering but I do work with some smart people in that field whom I can consult. I do have some experience with audio signal processing (though by no means an expert). By all means let me know what I can do to help!

**Comment by Thalhammer** [comment]
Basically I'd need someone with knowledge in those fields to glance over the reversed code and check if it makes sense. The issue is that while I have quite some experience in reversing stuff, I have virtually none in audio/ml stuff. So unless my tests fail I probably would not notice if what I am writing is complete garbage. If you consider using this, I am happy to hear (I'll probably add a list of users at some point, in case you want on it), but be aware that this is by no means stable software and certainly not production ready. I might also change the API at some point (definitly internal stuff, probably also the wrapper classes that where exposed in the original library) to make them easier/safer to use.

**Comment by sveinbjornt** [comment]
I'm currently making do with the binaries available via the Snowboy fork for production. However, your project here represents a real, possible open source future for this technology!

**Pull request merged**
